#include "FloorContainer.h"
#include "../UI/ChalkBoardBase.h"
#include "Classroom.h"
#include "../Core/MyPlayerCharacter.h"
#include "Components/SceneComponent.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "PassingThrough/Core/CustomizedPlayerController.h"
#include "PassingThrough/Systems/LocalGlobalSubsystem.h"

AFloorContainer::AFloorContainer()
{
	PrimaryActorTick.bCanEverTick = false;

	RootScene = CreateDefaultSubobject<USceneComponent>(TEXT("Scene"));
	RootComponent = RootScene;

	FloorBarrier = CreateDefaultSubobject<UBoxComponent>(TEXT("FloorBarrier"));
	FloorBarrier->SetupAttachment(RootComponent);
	FloorBarrier->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	FloorBarrier->SetHiddenInGame(true);

	DoorBarrier = CreateDefaultSubobject<UBoxComponent>(TEXT("DoorBarrier"));
	DoorBarrier->SetupAttachment(RootComponent);
	DoorBarrier->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	DoorBarrier->SetHiddenInGame(true);

	DoorTrigger = CreateDefaultSubobject<UBoxComponent>(TEXT("DoorTrigger"));
	DoorTrigger->SetupAttachment(RootComponent);
	DoorTrigger->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	DoorTrigger->SetGenerateOverlapEvents(true);
	DoorTrigger->SetCollisionProfileName(TEXT("Trigger"));
	DoorTrigger->SetRelativeLocation(FVector(-57.f, -4295.f, 0.f));
	DoorTrigger->OnComponentBeginOverlap.AddDynamic(this, &AFloorContainer::OnPlayerEnterTrigger);
}

void AFloorContainer::BeginPlay()
{
	Super::BeginPlay();
}

// íŠ¸ë¦¬ê±° ìƒíƒœ ê´€ë¦¬ í•¨ìˆ˜
void AFloorContainer::SetTriggerProcessing(bool bProcessing)
{
	bTriggerProcessing = bProcessing;

	if (bProcessing)
	{
		GetWorldTimerManager().SetTimer(
			TriggerTimeoutTimer,
			this,
			&AFloorContainer::OnTriggerTimeout,
			5.0f,
			false
		);
		UE_LOG(LogTemp, Log, TEXT("[%s] íŠ¸ë¦¬ê±° ì²˜ë¦¬ ì‹œì‘ (5ì´ˆ íƒ€ì„ì•„ì›ƒ)"), *GetName());
	}
	else
	{
		// íƒ€ì´ë¨¸ ì œê±°
		GetWorldTimerManager().ClearTimer(TriggerTimeoutTimer);
		UE_LOG(LogTemp, Log, TEXT("[%s] íŠ¸ë¦¬ê±° ì²˜ë¦¬ ì™„ë£Œ"), *GetName());
	}
}

// íƒ€ì„ì•„ì›ƒ ì•ˆì „ì¥ì¹˜
void AFloorContainer::OnTriggerTimeout()
{
	bTriggerProcessing = false;
}

void AFloorContainer::OnPlayerEnterTrigger(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	// í”Œë ˆì´ì–´ë§Œ ì²˜ë¦¬
	AMyPlayerCharacter* PlayerCharacter = Cast<AMyPlayerCharacter>(OtherActor);
	if (!PlayerCharacter)
	{
		return;
	}

	// ê°œë³„ íŠ¸ë¦¬ê±° ì¤‘ë³µ ë°©ì§€ ì²´í¬
	if (bTriggerProcessing)
	{
		return;
	}

	FVector PlayerLocation = PlayerCharacter->GetActorLocation();
	FVector ContainerLocation = GetActorLocation();
	FVector TriggerWorldLocation = DoorTrigger->GetComponentLocation();

	SetTriggerProcessing(true);

	// ì •ë‹µ/ì˜¤ë‹µ í™•ì¸
	APawn* PlayerPawn = Cast<APawn>(OtherActor);
	bool bIsCorrect = false;
	if (PlayerPawn)
	{
		ACustomizedPlayerController* PC = Cast<ACustomizedPlayerController>(PlayerPawn->GetController());
		if (PC)
		{
			bIsCorrect = PC->bLastAnswerCorrect;
		}
	}

	UGameInstance* GameInstance = UGameplayStatics::GetGameInstance(GetWorld());
	if (GameInstance)
	{
		ULocalGlobalSubsystem* Subsystem = GameInstance->GetSubsystem<ULocalGlobalSubsystem>();
		if (Subsystem && Subsystem->ClassroomManagerRef)
		{
			// íŠ¸ë¦¬ê±°ë¥¼ ì¦‰ì‹œ ë¹„í™œì„±í™” (ì¤‘ë³µ ë°©ì§€)
			if (DoorTrigger)
			{
				DoorTrigger->SetCollisionEnabled(ECollisionEnabled::NoCollision);
				// EnableBarriers();
			}

			// ì •ë‹µ/ì˜¤ë‹µ ëª¨ë‘ ë™ì¼í•œ ë¡œì§ ì‚¬ìš©ìœ¼ë¡œ ë³€ê²½
			Subsystem->ClassroomManagerRef->NextFloorWithContainer(this);

			if (!bIsCorrect)
			{
				Subsystem->ClassroomManagerRef->ResetCurrentClassNumber();
			}

			return;
		}
		else
		{
			// ì‹¤íŒ¨ ì‹œ í”Œë˜ê·¸ í•´ì œ
			SetTriggerProcessing(false);
		}
	}
}

void AFloorContainer::ClearPuzzle()
{
	if (IsValid(SpawnedPuzzle))
	{
		// ì•¡í„°ê°€ ì´ë¯¸ íŒŒê´´ ì¤‘ì¸ì§€ í™•ì¸
		if (!SpawnedPuzzle->IsPendingKillPending())
		{
			SpawnedPuzzle->Destroy();
		}
		SpawnedPuzzle = nullptr;
	}
	CurrentClassroomType = EClassroomType::None;
}

void AFloorContainer::SetClassroom(EClassroomType NewType, const TMap<EClassroomType, TSubclassOf<AClassroom>>& ClassroomBPMap)
{
	if (IsValid(SpawnedPuzzle))
	{
		UE_LOG(LogTemp, Warning, TEXT("[%s] ê¸°ì¡´ êµì‹¤ ê°•ì œ ì‚­ì œ: %s"), *GetName(), *SpawnedPuzzle->GetName());
		SpawnedPuzzle->Destroy();
		SpawnedPuzzle = nullptr;
	}
	CurrentClassroomType = EClassroomType::None;

	CurrentClassroomType = NewType;

	if (!ClassroomBPMap.Contains(NewType))
	{
		UE_LOG(LogTemp, Error, TEXT("[%s] êµì‹¤ íƒ€ì… %sì„ ClassroomBPMapì—ì„œ ì°¾ì„ ìˆ˜ ì—†ìŒ"),
			*GetName(), *UEnum::GetValueAsString(NewType));

		// ğŸ” ë””ë²„ê¹…: í˜„ì¬ ë§µì— ìˆëŠ” í‚¤ë“¤ ì¶œë ¥
		UE_LOG(LogTemp, Warning, TEXT("í˜„ì¬ ClassroomBPMapì— ë“±ë¡ëœ íƒ€ì…ë“¤:"));
		for (auto& Pair : ClassroomBPMap)
		{
			UE_LOG(LogTemp, Warning, TEXT("   - %s"), *UEnum::GetValueAsString(Pair.Key));
		}
		return;
	}

	TSubclassOf<AClassroom> ClassroomClass = ClassroomBPMap[NewType];
	if (!ClassroomClass)
	{
		UE_LOG(LogTemp, Error, TEXT("[%s] ClassroomClassê°€ nullptr"), *GetName());
		return;
	}

	FVector SpawnLocation = GetActorLocation();
	FRotator SpawnRotation = GetActorRotation();

	if (MarkingActor && IsValid(MarkingActor))
	{
		SpawnLocation = MarkingActor->GetActorLocation();
		SpawnRotation = MarkingActor->GetActorRotation();
	}

	FActorSpawnParameters SpawnParams;
	SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;

	// íƒ€ì„ìŠ¤íƒ¬í”„ë¡œ ì™„ì „ ê³ ìœ í•œ ì´ë¦„ ìƒì„±
	FString UniqueName = FString::Printf(TEXT("%s_Classroom_%s_%lld"),
		*GetName(),
		*UEnum::GetValueAsString(NewType),
		FDateTime::Now().GetTicks());
	SpawnParams.Name = FName(*UniqueName);

	// SpawnParams.Owner ì„¤ì •ìœ¼ë¡œ ì¶”ê°€ ì•ˆì „ì„±
	SpawnParams.Owner = this;


	SpawnedPuzzle = GetWorld()->SpawnActor<AClassroom>(ClassroomClass, SpawnLocation, SpawnRotation, SpawnParams);

	if (SpawnedPuzzle)
	{
		*GetName(), * UEnum::GetValueAsString(NewType), * SpawnLocation.ToString());

		// ì¹ íŒ ì°¾ê¸° ë° ë¬¸ì œ ì„¤ì •
		TArray<AActor*> ChalkBoards;
		UGameplayStatics::GetAllActorsOfClass(GetWorld(), AChalkBoardBase::StaticClass(), ChalkBoards);

		AChalkBoardBase* FoundChalkBoard = nullptr;
		float MinDistance = 1000.0f; // ìµœëŒ€ ê²€ìƒ‰ ê±°ë¦¬

		for (AActor* Actor : ChalkBoards)
		{
			AChalkBoardBase* ChalkBoard = Cast<AChalkBoardBase>(Actor);
			if (ChalkBoard)
			{
				AActor* ChalkBoardParent = ChalkBoard->GetAttachParentActor();
				float Distance = FVector::Dist(ChalkBoard->GetActorLocation(), SpawnLocation);

				// ë¶€ëª¨ê°€ ìŠ¤í°ëœ êµì‹¤ì´ë©´ ì¦‰ì‹œ ì„ íƒ
				if (ChalkBoardParent == SpawnedPuzzle)
				{
					FoundChalkBoard = ChalkBoard;
					break;
				}

				// ê·¸ë ‡ì§€ ì•Šìœ¼ë©´ ê°€ì¥ ê°€ê¹Œìš´ ì¹ íŒ ì„ íƒ
				if (Distance < MinDistance && !FoundChalkBoard)
				{
					FoundChalkBoard = ChalkBoard;
					MinDistance = Distance;
				}
			}
		}

		if (FoundChalkBoard && MathProblemsDataTable)
		{
			TArray<FMathProblemData*> AllRows;
			MathProblemsDataTable->GetAllRows<FMathProblemData>(TEXT(""), AllRows);

			if (AllRows.Num() > 0)
			{
				// ëœë¤ ì„ íƒ
				int32 RandomIndex = FMath::RandRange(0, AllRows.Num() - 1);
				FMathProblemData* SelectedProblem = AllRows[RandomIndex];

				FoundChalkBoard->SetProblemData(*SelectedProblem);
			}
		}
	}
	else
	{
		CurrentClassroomType = EClassroomType::None; // ì‹¤íŒ¨ ì‹œ íƒ€ì… ë¦¬ì…‹
	}
}

void AFloorContainer::EnableBarriers()
{
	UE_LOG(LogTemp, Error, TEXT("\n %s ë°°ë¦¬ì–´ í™œì„±í™”\n"), *GetActorLabel());

	// FloorBarrier->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	// DoorBarrier->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	OnBarrierStateChanged();

	// DoorBarrier->SetCollisionProfileName("BlockAll");
}

void AFloorContainer::DisableBarriers()
{
	UE_LOG(LogTemp, Error, TEXT("\n %s ë°°ë¦¬ì–´ ë¹„í™œì„±í™”\n"), *GetActorLabel());
	// FloorBarrier->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	// DoorBarrier->SetCollisionEnabled(ECollisionEnabled::NoCollision);

	// DoorBarrier->SetCollisionProfileName("NoCollision");
}

void AFloorContainer::ResetTrigger()
{
	if (!ClassroomManager)
	{
		if (UGameInstance* GameInstance = GetGameInstance())
		{
			if (ULocalGlobalSubsystem* Subsystem = GameInstance->GetSubsystem<ULocalGlobalSubsystem>())
			{
				ClassroomManager = Subsystem->GetClassroomManager();
			}
		}
	}

	if (!ClassroomManager)
	{
		UE_LOG(LogTemp, Error, TEXT("ClassroomManagerê°€ ì¡´ì¬í•˜ì§€ ì•ŠìŒ!"));
		return;
	}

	SetTriggerProcessing(false);
}
